import React, {useEffect,useState} from 'react';
import {ResponsiveContainer,ComposedChart,Bar,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {api} from './workspaceUtils';

export default function CapacityReport({revision,running}) {
  const [report,setReport]=useState(null),[capacity,setCapacity]=useState(700),[extended,setExtended]=useState(750),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function refresh(){try{const value=await api('/api/capacity-report');setReport(value);setCapacity(value.capacity);setExtended(value.extended_capacity);setError('');}catch(e){setReport(null);setError(e.message);}}
  useEffect(()=>{refresh();},[revision,running]);
  async function save(){setBusy(true);try{const value=await api('/api/report-capacity',{method:'POST',timeoutMs:180000,headers:{'Content-Type':'application/json'},body:JSON.stringify({capacity:Number(capacity),extended_capacity:Number(extended)})});await refresh();if(!value.publication.synced&&!value.publication.queued)setError(`Saved locally. Sheets update needs retry: ${value.publication.sync_error}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const total=(label,rows)=>({Date:label,...Object.fromEntries((report?.columns||[]).slice(1).map(column=>[column,rows.reduce((sum,row)=>sum+Number(row[column]||0),0)]))});
  const table=(title,rows)=><section className="table-section"><h2>{title}</h2><div className="table-scroll"><table><thead><tr>{report.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.Date} style={row.Date.includes('Total')?{fontWeight:700,background:'var(--surface-raised,#edf3f1)'}:undefined}>{report.columns.map(column=><td key={column}>{row[column]??0}</td>)}</tr>)}</tbody></table></div></section>;
  return <section className="daily-orders"><div className="monthly-actions"><label>Daily capacity<input type="number" min="0" step="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><label>Extended daily capacity<input type="number" min="0" step="1" value={extended} onChange={e=>setExtended(e.target.value)}/></label><button className="primary" disabled={busy||running} onClick={save}>{busy?'Saving…':'Save capacity'}</button></div>
    <p className="muted">Targets apply to dates with orders in the selected source. {report?.source==='Imported Excel'?'Every imported date is included, including earlier months.':'Select a date in Daily Orders to change the detailed month.'}</p>
    {error&&<p className="notice warning" role="alert">{error}</p>}
    {report&&<><p className="report-context">{report.source} · {report.scope_label||report.month}</p>{table('Monthly capacity',[...report.monthly,total(`${report.month.slice(0,4)} YTD Total`,report.monthly.filter(row=>row.Date.startsWith(report.month.slice(0,4))))])}{table('Daily capacity',[...report.daily,total('Total',report.daily)])}<section className="daily-chart" aria-label="Capacity report chart"><h2>Overall · {report.scope_label||report.month}</h2><div style={{height:360}}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={report.daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="Date"/><YAxis/><Tooltip/><Legend/><Bar dataKey="Received" fill="#315c9b" isAnimationActive={false}/><Bar dataKey="Completed" fill="#5ba4cf" isAnimationActive={false}/><Line dataKey="Capacity" stroke="#dc793b" dot={false} isAnimationActive={false}/><Line dataKey="Ext capacity" stroke="#8c93cf" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div></section></>}
  </section>;
}
